### ISSUE TITLE
Opening of log fails on Windows 10

### ISSUE THREAD

**Issue by martinpaljak** [open-eid/TeRa#10]
The URL is "C:/Users/Martin Paljak/tera_20170723_112402_214.log", pasting it to a browser successfully opens the log file, whereas clicking it in the app will give an error "Tembeldamise logi avamine ebaõnnestus:c:/Users/Martin Paljak/tera_20170723_112402_214.log"

**Comment by uudisaru** [comment]
Resolved with https://github.com/open-eid/TeRa/commit/1d8fd74e24273195aafebb43a071be05af9551d8
