### ISSUE TITLE
Debiani pakett

### ISSUE THREAD

**Issue by webwareklem** [open-eid/TeRa#3]
Paluks tekitada ka viimase stabiilse Debiani jaoks pakett, Ubuntu pakett eeldab uuemaid teeke kui Debianis on:

 qestidutil-tera sõltub pakist libqt5core5a (>= 5.5.0); igatahes:
  Süsteemis olev libqt5core5a:amd64 versioon on 5.3.2+dfsg-4+deb8u2.
 qestidutil-tera sõltub pakist libstdc++6 (>= 5.2); igatahes:
  Süsteemis olev libstdc++6:amd64 versioon on 4.9.2-10.

**Comment by Telgat** [comment]
Ametlikku Debiani tuge ei ole plaanis lisada. Mis aga ei tähenda, et Debiani tugi ei võiks tekkuda kogukonna toel, st kui keegi võtab kätte ja vajalikud muudatused ära teeb oleme me valmis Pull Requesti kaaluma.
