### ISSUE TITLE
Disable Game Bar on Windows 10

### ISSUE THREAD

**Issue by martinpaljak** [open-eid/TeRa#9]
Whenever starting TeRa on Windows 10 (15063.483) it is considered a game and the green game bar notification "press windows + G for ..." pops up. This does not happen with ID-card utility or DigiDoc (thus it should be possible for this app as well)

Relevant: https://stackoverflow.com/questions/42733116/qt-disable-windows-10-game-bar

**Comment by metsma** [comment]
Fixed by #22
